#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_MainL2

#include "Basic.hpp"

#include "Border_MainL_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-MainL2.Border-MainL2_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_MainL2_C final : public UBorder_MainL_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-MainL2_C">();
	}
	static class UBorder_MainL2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_MainL2_C>();
	}
};

}

