#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_List_M

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-List-M.ButtonStyle-List-M_C
// 0x0000 (0x0530 - 0x0530)
class UButtonStyle_List_M_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-List-M_C">();
	}
	static class UButtonStyle_List_M_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_List_M_C>();
	}
};

}

