#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Frontend_Lobby

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Frontend_Lobby.Frontend_Lobby_C
// 0x0008 (0x03A8 - 0x03A0)
class AFrontend_Lobby_C final : public AFortLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Frontend_Lobby(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Frontend_Lobby_C">();
	}
	static class AFrontend_Lobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontend_Lobby_C>();
	}
};

}

