#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LegacyBasicGradientFill

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LegacyBasicGradientFill.LegacyBasicGradientFill_C
// 0x0040 (0x0280 - 0x0240)
class ULegacyBasicGradientFill_C final : public UFortUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0240(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 ImageFill;                                         // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           Color_1;                                           // 0x0250(0x0010)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FLinearColor                           Color_2;                                           // 0x0260(0x0010)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FVector2D                              Brush_Size;                                        // 0x0270(0x0008)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         Rotation;                                          // 0x0278(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LegacyBasicGradientFill(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Set_Fill(const struct FLinearColor& Color_1_0, const struct FLinearColor& Color_2_0, float Rotation__0___1_);
	void Set_Brush_Size(const struct FVector2D& Brush_Size_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LegacyBasicGradientFill_C">();
	}
	static class ULegacyBasicGradientFill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULegacyBasicGradientFill_C>();
	}
};

}

