#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SlateContentCalloutMenu

#include "Basic.hpp"


namespace SDK::Params
{

// Function SlateContentCalloutMenu.SlateContentCalloutMenu_C.ExecuteUbergraph_SlateContentCalloutMenu
// 0x0004 (0x0004 - 0x0000)
struct SlateContentCalloutMenu_C_ExecuteUbergraph_SlateContentCalloutMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SlateContentCalloutMenu.SlateContentCalloutMenu_C.Get Size Box
// 0x0008 (0x0008 - 0x0000)
struct SlateContentCalloutMenu_C_Get_Size_Box final
{
public:
	class USizeBox*                               Size_Box;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

