#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_GameState

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Athena_GameState.Athena_GameState_C
// 0x0008 (0x14E8 - 0x14E0)
class AAthena_GameState_C final : public AFortGameStateAthena
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x14E0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_GameState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_GameState_C")
	}
	static class AAthena_GameState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_GameState_C>();
	}
};

SDK_NAMESPACE_END
