#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaKillFeedItem

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass AthenaKillFeedItem.AthenaKillFeedItem_C
// 0x0010 (0x0270 - 0x0260)
class UAthenaKillFeedItem_C final : public UFortHUDElementWidget
{
public:
	class UFortRichTextBlock*                     KIllText;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class AFortGameStateAthena*                   GameState;                                         // 0x0268(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetText(const class FText& Text);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaKillFeedItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaKillFeedItem_C")
	}
	static class UAthenaKillFeedItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaKillFeedItem_C>();
	}
};

SDK_NAMESPACE_END
