#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_SupplyDropCameraShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass B_SupplyDropCameraShake.B_SupplyDropCameraShake_C
// 0x0000 (0x0160 - 0x0160)
class UB_SupplyDropCameraShake_C final : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_SupplyDropCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_SupplyDropCameraShake_C")
	}
	static class UB_SupplyDropCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_SupplyDropCameraShake_C>();
	}
};

SDK_NAMESPACE_END
