#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_ModalHeader_Recycle

#include "Basic.hpp"

#include "Border_ModalHeader_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Border-ModalHeader-Recycle.Border-ModalHeader-Recycle_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_ModalHeader_Recycle_C final : public UBorder_ModalHeader_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Border-ModalHeader-Recycle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Border-ModalHeader-Recycle_C")
	}
	static class UBorder_ModalHeader_Recycle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_ModalHeader_Recycle_C>();
	}
};

SDK_NAMESPACE_END
