#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ZT_Athena_Faceoff

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ZT_Athena_Faceoff.BP_ZT_Athena_Faceoff_C
// 0x0000 (0x0270 - 0x0270)
class UBP_ZT_Athena_Faceoff_C final : public UFortZoneTheme
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ZT_Athena_Faceoff_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ZT_Athena_Faceoff_C")
	}
	static class UBP_ZT_Athena_Faceoff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ZT_Athena_Faceoff_C>();
	}
};

SDK_NAMESPACE_END
