#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BuildWatermark

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BuildWatermark.BuildWatermark_C.ExecuteUbergraph_BuildWatermark
// 0x0004 (0x0004 - 0x0000)
struct BuildWatermark_C_ExecuteUbergraph_BuildWatermark final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BuildWatermark.BuildWatermark_C.Update Watermark
// 0x0030 (0x0030 - 0x0000)
struct BuildWatermark_C_Update_Watermark final
{
public:
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetWatermark_ReturnValue;                 // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
