#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Button_SkillTree_Next_L

#include "Basic.hpp"

#include "Button_SkillTree_L_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Button-SkillTree-Next-L.Button-SkillTree-Next-L_C
// 0x0000 (0x0530 - 0x0530)
class UButton_SkillTree_Next_L_C final : public UButton_SkillTree_L_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Button-SkillTree-Next-L_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Button-SkillTree-Next-L_C")
	}
	static class UButton_SkillTree_Next_L_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButton_SkillTree_Next_L_C>();
	}
};

SDK_NAMESPACE_END
