#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Hamburger

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ButtonStyle-Hamburger.ButtonStyle-Hamburger_C
// 0x0000 (0x0530 - 0x0530)
class UButtonStyle_Hamburger_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ButtonStyle-Hamburger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ButtonStyle-Hamburger_C")
	}
	static class UButtonStyle_Hamburger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Hamburger_C>();
	}
};

SDK_NAMESPACE_END
