#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CheckRateExperienceAction

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CheckRateExperienceAction.CheckRateExperienceAction_C
// 0x0010 (0x03F8 - 0x03E8)
class ACheckRateExperienceAction_C final : public AFortScriptedAction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E8(0x0008)(Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CheckRateExperienceAction(int32 EntryPoint);
	void Execute(const struct FFortScriptedActionParams& Params_0);
	void HandleClientEvent_FinishedModalQueue(class UObject* EventSource, class UObject* EventFocus, const struct FFortClientEvent& ClientEvent);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CheckRateExperienceAction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CheckRateExperienceAction_C")
	}
	static class ACheckRateExperienceAction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACheckRateExperienceAction_C>();
	}
};

SDK_NAMESPACE_END
