#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CollectionBookWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass CollectionBookWidget.CollectionBookWidget_C
// 0x0008 (0x0448 - 0x0440)
class UCollectionBookWidget_C final : public UFortCollectionBookWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0440(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_CollectionBookWidget(int32 EntryPoint);
	void OnActivated();
	void Destruct();
	void SlotItemComplete(const class UFortAccountItem* ItemSlotted, class FName SlotId);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CollectionBookWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CollectionBookWidget_C")
	}
	static class UCollectionBookWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCollectionBookWidget_C>();
	}
};

SDK_NAMESPACE_END
