#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CollectionBookPrimaryPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass CollectionBookPrimaryPanel.CollectionBookPrimaryPanel_C
// 0x0010 (0x04B0 - 0x04A0)
class UCollectionBookPrimaryPanel_C final : public UFortCollectionBookPrimaryPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(Transient, DuplicateTransient)
	bool                                          CanShowCollectionBookHelp;                         // 0x04A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_CollectionBookPrimaryPanel(int32 EntryPoint);
	void HandleDisplayInfoBox();
	void OnSummonInfoPanelExecuted(bool* bPassThrough);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CollectionBookPrimaryPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CollectionBookPrimaryPanel_C")
	}
	static class UCollectionBookPrimaryPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCollectionBookPrimaryPanel_C>();
	}
};

SDK_NAMESPACE_END
