#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComingSoonPlaceholderWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass ComingSoonPlaceholderWidget.ComingSoonPlaceholderWidget_C
// 0x0018 (0x0248 - 0x0230)
class UComingSoonPlaceholderWidget_C final : public UUserWidget
{
public:
	class UImage*                                 Image_0;                                           // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       UnderConstruction;                                 // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ComingSoonPlaceholderWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ComingSoonPlaceholderWidget_C")
	}
	static class UComingSoonPlaceholderWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UComingSoonPlaceholderWidget_C>();
	}
};

SDK_NAMESPACE_END
