#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Frontend

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Frontend.FrontEnd_C
// 0x0010 (0x03B0 - 0x03A0)
class AFrontEnd_C final : public AFortLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(Transient, DuplicateTransient)
	class AHBOnboardingFlow_C*                    HBOnboardingFlow_ExecuteUbergraph_Frontend_RefProperty; // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FrontEnd(int32 EntryPoint);
	void EnableTutorial();
	void ReceiveBeginPlay();
	void OnMatchStarted();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FrontEnd_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FrontEnd_C")
	}
	static class AFrontEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontEnd_C>();
	}
};

SDK_NAMESPACE_END
