#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Ninja_DimMak

#include "Basic.hpp"

#include "GA_Ninja_DimMak_classes.hpp"
#include "GA_Ninja_DimMak_parameters.hpp"


SDK_NAMESPACE_START

SDK_NAMESPACE_END
