#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Ninja_ShadowStance

#include "Basic.hpp"

#include "GA_Ninja_ShadowStance_classes.hpp"
#include "GA_Ninja_ShadowStance_parameters.hpp"


SDK_NAMESPACE_START

SDK_NAMESPACE_END
