#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Commando_AmmoRecoveryCooldown

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Commando_AmmoRecoveryCooldown.GE_Commando_AmmoRecoveryCooldown_C
// 0x0000 (0x0660 - 0x0660)
class UGE_Commando_AmmoRecoveryCooldown_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Commando_AmmoRecoveryCooldown_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Commando_AmmoRecoveryCooldown_C")
	}
	static class UGE_Commando_AmmoRecoveryCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Commando_AmmoRecoveryCooldown_C>();
	}
};

SDK_NAMESPACE_END
