#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Commando_HeavilyArmored

#include "Basic.hpp"

#include "GE_Commando_Armored_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Commando_HeavilyArmored.GE_Commando_HeavilyArmored_C
// 0x0000 (0x0660 - 0x0660)
class UGE_Commando_HeavilyArmored_C final : public UGE_Commando_Armored_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Commando_HeavilyArmored_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Commando_HeavilyArmored_C")
	}
	static class UGE_Commando_HeavilyArmored_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Commando_HeavilyArmored_C>();
	}
};

SDK_NAMESPACE_END
