#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Map_Commando_Offense_AllWeaponDamage

#include "Basic.hpp"

#include "GE_Map_Offense_To_WeaponDamage_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Map_Commando_Offense_AllWeaponDamage.GE_Map_Commando_Offense_AllWeaponDamage_C
// 0x0000 (0x0660 - 0x0660)
class UGE_Map_Commando_Offense_AllWeaponDamage_C final : public UGE_Map_Offense_To_WeaponDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Map_Commando_Offense_AllWeaponDamage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Map_Commando_Offense_AllWeaponDamage_C")
	}
	static class UGE_Map_Commando_Offense_AllWeaponDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Map_Commando_Offense_AllWeaponDamage_C>();
	}
};

SDK_NAMESPACE_END
