#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GET_DirectPhysicalDamage

#include "Basic.hpp"

#include "Get_DirectDamageParent_classes.hpp"


SDK_NAMESPACE_START

SDK_NAMESPACE_END
