#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hero_Management_HUDWrapper

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass Hero_Management_HUDWrapper.Hero_Management_HUDWrapper_C
// 0x0018 (0x0258 - 0x0240)
class UHero_Management_HUDWrapper_C final : public UFortUserWidget
{
public:
	class UImage*                                 Fill;                                              // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Frame;                                             // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Pattern;                                           // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Hero_Management_HUDWrapper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Hero_Management_HUDWrapper_C")
	}
	static class UHero_Management_HUDWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHero_Management_HUDWrapper_C>();
	}
};

SDK_NAMESPACE_END
