#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroNotificationHandler

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass HeroNotificationHandler.HeroNotificationHandler_C
// 0x0000 (0x01F0 - 0x01F0)
class UHeroNotificationHandler_C final : public UFortHeroNotificationHandler
{
public:
	class UUserWidget* CreateWidget(class APlayerController* OwningPlayer);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HeroNotificationHandler_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HeroNotificationHandler_C")
	}
	static class UHeroNotificationHandler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeroNotificationHandler_C>();
	}
};

SDK_NAMESPACE_END
