#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HomeScreenQuestRewardItem

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function HomeScreenQuestRewardItem.HomeScreenQuestRewardItem_C.ExecuteUbergraph_HomeScreenQuestRewardItem
// 0x0004 (0x0004 - 0x0000)
struct HomeScreenQuestRewardItem_C_ExecuteUbergraph_HomeScreenQuestRewardItem final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
