#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemCooldownMeter

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass ItemCooldownMeter.ItemCooldownMeter_C
// 0x02F0 (0x0520 - 0x0230)
class UItemCooldownMeter_C final : public UUserWidget
{
public:
	class UImage*                                 _Image__Backfill;                                  // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 _Image__Overfill;                                  // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               _SizeBox_;                                         // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             _Text__Clock;                                      // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FFortMultiSizeFont                     MultiSizeFont;                                     // 0x0250(0x0270)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FFortMultiSizeMargin                   MultiSizeMargin;                                   // 0x04C0(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void Update(EFortBrushSize Brush_Size);
	void Set_Cooldown(const struct FTimespan& Time_Left);
	int32 GetSecondsCorrectedMinutes(int32 Minutes, int32 Seconds);
	void GetCooldownMaterial(class UMaterialInstanceDynamic** CooldownMat);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemCooldownMeter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemCooldownMeter_C")
	}
	static class UItemCooldownMeter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemCooldownMeter_C>();
	}
};

SDK_NAMESPACE_END
