#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemManagementFocusSwitcher

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass ItemManagementFocusSwitcher.ItemManagementFocusSwitcher_C
// 0x0020 (0x0258 - 0x0238)
class UItemManagementFocusSwitcher_C final : public UCommonUserWidget
{
public:
	class UIconTabButton_C*                       IconTabButton;                                     // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortItemTileView*                      TileViewA;                                         // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemTileView*                      TileViewB;                                         // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemTileView*                      PreviousFocus;                                     // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	void DeferFocusSwitch();
	void ExecuteFocusSwitch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemManagementFocusSwitcher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemManagementFocusSwitcher_C")
	}
	static class UItemManagementFocusSwitcher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemManagementFocusSwitcher_C>();
	}
};

SDK_NAMESPACE_END
