#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LegacyButtonStyle_Base

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LegacyButtonStyle-Base.LegacyButtonStyle-Base_C
// 0x0000 (0x1C08 - 0x1C08)
class ULegacyButtonStyle_Base_C : public UFortButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LegacyButtonStyle-Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LegacyButtonStyle-Base_C")
	}
	static class ULegacyButtonStyle_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULegacyButtonStyle_Base_C>();
	}
};

SDK_NAMESPACE_END
