#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LegacyPerkTierWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass LegacyPerkTierWidget.LegacyPerkTierWidget_C
// 0x0030 (0x0290 - 0x0260)
class ULegacyPerkTierWidget_C final : public UFortPerkTierWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(Transient, DuplicateTransient)
	class UVerticalBox*                           PerkList;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULegacyPerkWidget_C*                    PerkWidget;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULegacyPerkWidget_C*                    PerkWidget_0;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULegacyPerkWidget_C*                    PerkWidget_1;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bTextOnly;                                         // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_LegacyPerkTierWidget(int32 EntryPoint);
	void OnGeneratePerk(const struct FFortUIPerk& Perk);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LegacyPerkTierWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LegacyPerkTierWidget_C")
	}
	static class ULegacyPerkTierWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULegacyPerkTierWidget_C>();
	}
};

SDK_NAMESPACE_END
