#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionBotPawn

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MissionBotPawn.MissionBotPawn_C
// 0x0000 (0x1AF0 - 0x1AF0)
class AMissionBotPawn_C final : public AFortBotPawn
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MissionBotPawn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MissionBotPawn_C")
	}
	static class AMissionBotPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMissionBotPawn_C>();
	}
};

SDK_NAMESPACE_END
