#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NavFilter_MissionBots

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass NavFilter_MissionBots.NavFilter_MissionBots_C
// 0x0000 (0x0048 - 0x0048)
class UNavFilter_MissionBots_C final : public UNavigationQueryFilter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NavFilter_MissionBots_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NavFilter_MissionBots_C")
	}
	static class UNavFilter_MissionBots_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNavFilter_MissionBots_C>();
	}
};

SDK_NAMESPACE_END
