#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PermissionsRoot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass PermissionsRoot.PermissionsRoot_C
// 0x0038 (0x0418 - 0x03E0)
class UPermissionsRoot_C final : public UCommonActivatablePanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(Transient, DuplicateTransient)
	class UCommonWidgetSwitcher*                  Outpost_Screen_WidgetSwitcher;                     // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       OutpostLevel_Text;                                 // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       OutpostName_Text;                                  // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOutpostScreenStormShieldPermissions_C* OutpostScreenStormShieldPermissions;               // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPlayerBanner_C*                        PlayerBanner;                                      // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_2;                                        // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PermissionsRoot(int32 EntryPoint);
	void OnActivated();
	void Construct();
	void RefreshOutpostInfo();
	void Input_Handle_Back(bool* PassThrough);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PermissionsRoot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PermissionsRoot_C")
	}
	static class UPermissionsRoot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPermissionsRoot_C>();
	}
};

SDK_NAMESPACE_END
