#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerPawn_Ninja

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PlayerPawn_Generic_classes.hpp"
#include "FortniteGame_structs.hpp"
#include "GameplayAbilities_structs.hpp"


SDK_NAMESPACE_START

SDK_NAMESPACE_END
