#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProgressModalWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass ProgressModalWidget.ProgressModalWidget_C
// 0x00E8 (0x04F0 - 0x0408)
class UProgressModalWidget_C final : public UFortActivatablePanel
{
public:
	uint8                                         Pad_408[0x8];                                      // 0x0408(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0410(0x0008)(Transient, DuplicateTransient)
	class ULightbox_C*                            Lightbox;                                          // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressWidget_C*                      ProgressWidget;                                    // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Title;                                             // 0x0428(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FText                                   Description;                                       // 0x0440(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FSlateBrush                            Icon;                                              // 0x0458(0x0090)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          bIntroOutrEnabled;                                 // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bAutoInitialize;                                   // 0x04E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bFocusSelf;                                        // 0x04EA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bConsumeAnalogInput;                               // 0x04EB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_ProgressModalWidget(int32 EntryPoint);
	void Destruct();
	void OnBeginOutro();
	void OnBeginIntro();
	void HandleOutroEnded();
	void HandleIntroEnded();
	void Construct();
	void Initialize();
	void SetTitle(const class FText& Title_0);
	void SetDescription(const class FText& Description_0);
	void SetIcon(const struct FSlateBrush& Icon_0);
	struct FEventReply OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ProgressModalWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ProgressModalWidget_C")
	}
	static class UProgressModalWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UProgressModalWidget_C>();
	}
};

SDK_NAMESPACE_END
