#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuickbarSlotCooldown

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ItemDisplayStyle_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass QuickbarSlotCooldown.QuickbarSlotCooldown_C
// 0x0028 (0x02F0 - 0x02C8)
class UQuickbarSlotCooldown_C final : public UFortItemCooldownWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 ImageRadialOpacityLayer;                           // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageRectangularOpacityLayer;                      // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonWidgetSwitcher*                  SwitcherOpacityOverlay;                            // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EItemDisplayStyle                             ItemDisplayStyle;                                  // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QuickbarSlotCooldown(int32 EntryPoint);
	void OnCooldownStopped(EFortItemCooldownType CooldownType);
	void OnCooldownStarted(EFortItemCooldownType CooldownType);
	void Show_Countdown(bool Show);
	void Initialize(EItemDisplayStyle QuickbarItemDisplayStyle, TArray<EFortItemCooldownType>& DesiredCooldownTypesSupported);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QuickbarSlotCooldown_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuickbarSlotCooldown_C")
	}
	static class UQuickbarSlotCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuickbarSlotCooldown_C>();
	}
};

SDK_NAMESPACE_END
