#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_Header_L_Blue2

#include "Basic.hpp"

#include "TextStyle_Header_L_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TextStyle-Header-L-Blue2.TextStyle-Header-L-Blue2_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyle_Header_L_Blue2_C final : public UTextStyle_Header_L_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TextStyle-Header-L-Blue2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TextStyle-Header-L-Blue2_C")
	}
	static class UTextStyle_Header_L_Blue2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Header_L_Blue2_C>();
	}
};

SDK_NAMESPACE_END
