#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_Base_S_S_LightGray

#include "Basic.hpp"

#include "TextStyle_Base_S_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TextStyle-Base-S-S_LightGray.TextStyle-Base-S-S_LightGray_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyle_Base_S_S_LightGray_C final : public UTextStyle_Base_S_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TextStyle-Base-S-S_LightGray_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TextStyle-Base-S-S_LightGray_C")
	}
	static class UTextStyle_Base_S_S_LightGray_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Base_S_S_LightGray_C>();
	}
};

SDK_NAMESPACE_END
