#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_Power_S_S

#include "Basic.hpp"

#include "TextStyle_Power_S_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TextStyle-Power-S-S.TextStyle-Power-S-S_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyle_Power_S_S_C final : public UTextStyle_Power_S_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TextStyle-Power-S-S_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TextStyle-Power-S-S_C")
	}
	static class UTextStyle_Power_S_S_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Power_S_S_C>();
	}
};

SDK_NAMESPACE_END
