#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TT_Ninja_MantisLeap

#include "Basic.hpp"

#include "TT_Ninja_MantisLeap_classes.hpp"
#include "TT_Ninja_MantisLeap_parameters.hpp"


SDK_NAMESPACE_START

SDK_NAMESPACE_END
